# ==================== API Key ====================
langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.streaming-chat-model.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.streaming-chat-model.base-url=https://api.lkeap.cloud.tencent.com/plan/v3
langchain4j.open-ai.streaming-chat-model.model-name=minimax-m2.5
langchain4j.open-ai.streaming-chat-model.temperature=0.7
langchain4j.open-ai.streaming-chat-model.log-requests=true
langchain4j.open-ai.streaming-chat-model.log-responses=true


#MongoDB????
spring.data.mongodb.uri=mongodb://localhost:27017/chat_memory_db


spring.datasource.url=jdbc:mysql://localhost:3306/guiguxiaozhi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ?? SQL ????
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl