spring.profiles.active=dev

# web??????
server.port=8079

#langchain4
langchain4j.open-ai.chat-model.base-url=https://api.lkeap.cloud.tencent.com/plan/v3

langchain4j.open-ai.chat-model.model-name=minimax-m2.5
#???????????? 0 ? 1 ??????????????????????
# ?????????????????? 0.9?????????????????????????????
langchain4j.open-ai.chat-model.temperature=0.9


#???????
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true

#????debug??
logging.level.root=info

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


